name: Notion-Google Tasks Sync

on:
  schedule:
    - cron: '*/5 21-23,0-13 * * *'  # 한국 시간 06:00-22:00 사이 5분마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create credential files
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" > .env
          echo "NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}" >> .env
          echo "GOOGLE_TASKLIST_ID=${{ secrets.GOOGLE_TASKLIST_ID }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
      
      - name: Run sync script
        run: python notion_google_sync.py 