name: Google Token Refresh

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 UTC 00:00 (한국 시간 09:00)에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create credential files
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.GOOGLE_TOKEN }}" > token.json
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" > .env
          echo "NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}" >> .env
          echo "GOOGLE_TASKLIST_ID=${{ secrets.GOOGLE_TASKLIST_ID }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
      
      - name: Run token refresh script
        run: python token_refresh.py 